spring:
  config:
    import: optional:file:./.env[.properties]
  docker:
    compose:
      lifecycle-management: start-and-stop
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 25
